/*
 * config.h — all tunables for the Veg flight controller in one place.
 *
 * Conventions used everywhere in the firmware (after the sign flags below):
 *   roll  > 0  : right side down            (degrees)
 *   pitch > 0  : nose up                    (degrees)
 *   yaw rate > 0 : nose turns right (clockwise seen from above)  (deg/s)
 *
 * Motor layout (X-quad, seen from above, nose up the page) — this matches the
 * mixing in the original Veg firmware, so existing wiring does not change:
 *
 *        M4 (D9)  front-left   CW prop      M3 (D6)  front-right  CCW prop
 *                          \              /
 *                           \    FRONT   /
 *                            +----------+
 *                           /            \
 *                          /              \
 *        M1 (D3)  rear-left    CCW prop     M2 (D5)  rear-right   CW prop
 *
 * If your props spin the other way, flip YAW_MIX_SIGN.
 * If a bench test (props OFF) shows the wrong motor speeding up, flip the
 * matching *_SIGN flag — never swap gains to "fix" a sign.
 */
#pragma once

// ---------------- Controller selection ----------------
#define CONTROL_MODE_PID 1
#define CONTROL_MODE_LQR 2
#define DEFAULT_CONTROL_MODE CONTROL_MODE_LQR   // can also be changed at runtime: "MODE PID" / "MODE LQR" (disarmed only)

// ---------------- Loop timing ----------------
#define LOOP_HZ            250
#define LOOP_US            (1000000UL / LOOP_HZ)
#define TELEMETRY_HZ       10

// ---------------- Serial link / failsafe ----------------
#define SERIAL_BAUD        115200
#define LINK_TIMEOUT_MS    500     // no valid SET for this long while armed -> FAILSAFE
#define FS_THROTTLE        0.35f   // throttle held during failsafe descent (set BELOW your hover throttle)
#define FS_RAMP_PER_S      0.25f   // how fast throttle is reduced toward FS_THROTTLE (per second; never increased)
#define FS_DESCENT_MS      8000    // after this long in failsafe, motors are stopped (no altitude sensor!)

// ---------------- Safety limits ----------------
#define MAX_ANGLE_CMD_DEG  25.0f   // roll/pitch setpoints are clamped to +/- this
#define MAX_YAW_RATE_DPS   120.0f
#define ARM_MAX_TILT_DEG   10.0f   // must be roughly level to arm
#define ARM_MAX_THROTTLE   0.05f   // throttle stick must be low to arm
#define CRASH_TILT_DEG     60.0f   // beyond this while armed -> immediate motor cut
#define I_ENABLE_THROTTLE  0.15f   // integrators frozen/reset below this throttle (on the ground)

// ---------------- ESC / motor output (microseconds) ----------------
#define MOTOR_OFF_US       1000    // sent whenever disarmed
#define MOTOR_IDLE_US      1100    // armed, zero throttle (props spin slowly)
#define MOTOR_MAX_US       1900
const uint8_t MOTOR_PINS[4] = {3, 5, 6, 9};   // M1..M4 (see diagram above)

// Mixer signs per motor: {roll, pitch, yaw}. Matches the original Veg mixing.
const int8_t MIX[4][3] = {
  { +1, -1, +1 },   // M1 rear-left
  { -1, -1, -1 },   // M2 rear-right
  { -1, +1, +1 },   // M3 front-right
  { +1, +1, -1 },   // M4 front-left
};
#define YAW_MIX_SIGN       (+1)

// ---------------- IMU (MPU6050) ----------------
// Default assumes the chip's X arrow points FORWARD and the chip faces UP.
#define IMU_ROLL_SIGN      (+1)
#define IMU_PITCH_SIGN     (-1)
#define IMU_YAW_SIGN       (-1)
#define GYRO_LSB_PER_DPS   65.5f   // +/-500 dps range
#define COMP_FILTER_ALPHA  0.98f   // complementary filter: weight on gyro
#define ACCEL_TRUST_MIN_G  0.8f    // only use accel correction when |a| is near 1 g
#define ACCEL_TRUST_MAX_G  1.2f
#define ROLL_TRIM_DEG      0.0f    // level trim if the IMU is not mounted perfectly flat
#define PITCH_TRIM_DEG     0.0f
#define GYRO_CAL_SAMPLES   500
#define GYRO_CAL_MAX_DEV   2.0f    // deg/s — calibration rejected if the drone moved

// ---------------- Gains (output units: microseconds of ESC pulse) ----------------
// LQR state feedback: u = K0*(angle_ref - angle) - K1*rate
// Generated by veg-slam-drone-sim/compute_lqr_gains.m from veg_plant_parameters.mat
// (closed-loop poles ~ -9.7 rad/s). Re-run it after measuring kT_us on a thrust stand.
const float K_ROLL[2]  = { 4.472f, 0.903f };
const float K_PITCH[2] = { 4.472f, 0.903f };

// Angle PID (D term acts on gyro rate, not on differentiated angle)
const float PID_ROLL[3]  = { 6.0f, 1.5f, 1.75f };   // Kp, Ki, Kd
const float PID_PITCH[3] = { 5.0f, 3.0f, 3.0f };

// Yaw is rate-controlled in both modes (gyro-only yaw angle drifts)
const float PID_YAW_RATE[2] = { 2.0f, 0.5f };      // Kp, Ki

#define I_LIMIT_US         100.0f  // anti-windup clamp on each integrator's contribution
