
# EuRoC.yaml for monocular-inertial setup

Camera:
  fps: 10.0
  cols: 640
  rows: 480
  fx: 520.9
  fy: 521.0
  cx: 325.1
  cy: 249.7
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

IMU:
  NoiseGyro: 0.0001
  NoiseAcc: 0.0002
  GyroWalk: 0.00001
  AccWalk: 0.00002
  Freq: 200
  ThDepth: 35.0
